name: Deploy HTML to EC2

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Show all files
      run: ls -al
      
    - name: Execute remote SSH commands using SSH
      uses: appleboy/ssh-action@v1
      with:
          host: ${{ secrets.EC2_JIGAR }}
          username: ${{ secrets.EC2_USERS }}
          key: $ {{ secrets.EC2_PASS }}
          port: 22
          script: |
            whoami
            pwd
            ls -al
            mkdir Jigar
            
          
